import type { Metadata } from "next";
import "./globals.css";
import { Header, Toggle } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="h-screen w-screen bg-gray-900">
        <Header />
        {children}
      </body>
    </html>
  );
}
